import "../styles/globals.css"
import type { AppProps } from "next/app"
import Head from "next/head"
import { RecoilRoot } from "recoil"

function MyApp({ Component, pageProps }: AppProps) {
	return (
		<RecoilRoot>
			<Head>
				<title>Tront</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/logo.svg" />
			</Head>
			<Component {...pageProps} />
		</RecoilRoot>
	)
}

export default MyApp
